import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const projectRoot = path.dirname(root.endsWith("site") ? root : path.join(root, "site"));
const siteRoot = root.endsWith("site") ? root : path.join(root, "site");
const sourceRoot = path.join(projectRoot, "krok");
const outputPath = path.join(siteRoot, "src/content/krok/generated.ts");

const sources = [
  {
    id: "2024",
    title: "КРОК 3 Неврологія 2024",
    year: 2024,
    sourceFile: "Krok_3_Nevrologiya_2024_questions_answers.docx"
  },
  {
    id: "2025",
    title: "КРОК 3 Неврологія 2025",
    year: 2025,
    sourceFile: "Krok_3_Nevrologiya_2025_questions_answers.docx"
  },
  {
    id: "2026",
    title: "КРОК 3 Неврологія 2026",
    year: 2026,
    sourceFile: "Krok_3_Nevrologiya_2026_questions_answers.docx"
  }
];

function readDocxText(filePath) {
  return execFileSync("textutil", ["-convert", "txt", "-stdout", filePath], {
    encoding: "utf8",
    maxBuffer: 1024 * 1024 * 12
  })
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n");
}

function parseBooklet(source) {
  const filePath = path.join(sourceRoot, source.sourceFile);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing KROK source file: ${filePath}`);
  }

  const text = readDocxText(filePath);
  const starts = [...text.matchAll(/^(?:Вопрос|Питання)\s+(\d+)\s*$/gm)].map((match) => ({
    number: Number(match[1]),
    index: match.index
  }));

  if (starts.length !== 150) {
    throw new Error(`${source.id}: expected 150 questions, got ${starts.length}`);
  }

  const questions = starts.map((start, index) => {
    const nextIndex = starts[index + 1]?.index ?? text.length;
    const chunk = text.slice(start.index, nextIndex).trim();
    const optionMatches = [...chunk.matchAll(/^([a-e])\.\s+(.+)$/gm)];
    const correctMatch = chunk.match(/^Правильн(?:ый ответ|а відповідь):\s*([a-e])\.\s+(.+)$/m);

    if (!correctMatch) {
      throw new Error(`${source.id} question ${start.number}: missing correct answer`);
    }
    if (optionMatches.length < 3 || optionMatches.length > 5) {
      throw new Error(
        `${source.id} question ${start.number}: expected 3-5 options, got ${optionMatches.length}`
      );
    }

    const firstOptionIndex = optionMatches[0].index ?? -1;
    if (firstOptionIndex < 0) {
      throw new Error(`${source.id} question ${start.number}: missing first option index`);
    }

    const questionText = chunk
      .slice(chunk.indexOf("\n") + 1, firstOptionIndex)
      .replace(/\n+/g, " ")
      .replace(/\s+/g, " ")
      .trim();

    const options = optionMatches.map((match) => ({
      id: `${source.id}-${String(start.number).padStart(3, "0")}-${match[1]}`,
      sourceLetter: match[1],
      text: match[2].replace(/\s+/g, " ").trim()
    }));
    const correctLetter = correctMatch[1];
    const correctOption = options.find((option) => option.sourceLetter === correctLetter);
    if (!correctOption) {
      throw new Error(`${source.id} question ${start.number}: correct option missing`);
    }

    return {
      id: `${source.id}-${String(start.number).padStart(3, "0")}`,
      bookletId: source.id,
      sourceNumber: start.number,
      text: questionText,
      options,
      correctOptionId: correctOption.id
    };
  });

  const seen = new Set();
  for (const question of questions) {
    if (seen.has(question.id)) {
      throw new Error(`${source.id}: duplicate question id ${question.id}`);
    }
    seen.add(question.id);
  }

  return {
    id: source.id,
    title: source.title,
    year: source.year,
    sourceFile: source.sourceFile,
    questions
  };
}

const booklets = sources.map(parseBooklet);
const questionCount = booklets.reduce((sum, booklet) => sum + booklet.questions.length, 0);
if (questionCount !== 450) {
  throw new Error(`Expected 450 KROK questions, got ${questionCount}`);
}

const output = `import type { KrokBooklet } from "./schema";

// Generated by scripts/import-krok.mjs. Do not edit by hand.
export const krokBooklets = ${JSON.stringify(booklets, null, 2)} satisfies KrokBooklet[];
`;

fs.writeFileSync(outputPath, output);
console.log(`Imported ${booklets.length} KROK booklets, ${questionCount} questions -> ${outputPath}`);
